export const icons = {
  app_dev: require('./source/app_dev.png'),
  app_test: require('./source/app_test.png'),
  app_prod: require('./source/app_prod.png'),
  send: require('./source/send.png'),
  back: require('./source/arrow-back.png'),
  bullet: require('./source/bullet.png'),
  close: require('./source/ic_close.png'),
  plus: require('./source/ic_plus.png'),
  home: require('./source/ic_home.png'),
  heart: require('./source/ic_heart.png'),
  search: require('./source/ic_search.png'),
  user: require('./source/ic_user.png'),
  arrow_down: require('./source/arrow_down.png'),
  check: require('./source/check.png'),
  minus: require('./source/minus.png'),
  edit: require('./source/edit.png'),
  logout: require('./source/logout.png'),
  order: require('./source/order.png'),
  seeCurrent: require('./source/seeCurrent.png'),
  trash: require('./source/trash.png'),
  coin: require('./source/coin.png'),
  vip: require('./source/vip.png'),
};

export type IconTypes = keyof typeof icons;
