export const GET_DATA_CINEMAS_PAGE = 'GET_DATA_CINEMAS_PAGE';
export const GET_LIST_CINEMAS = 'GET_LIST_CINEMAS';
export const GET_LIST_SHOWTIME_BY_CINEMAS = 'GET_LIST_SHOWTIME_BY_CINEMAS';
export const GET_LIST_SEAT_BY_SCREEN = 'GET_LIST_SEAT_BY_SCREEN';
export const GET_LIST_PRODUCTS = 'GET_LIST_PRODUCTS';
export const BOOK_TICKET = 'BOOK_TICKET';
